id: IBBEEE677
legacy_id: P007026
ocr_import_info:
  bdrc_scan_id: W1KG22381
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T23:25:09'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T13:11:32.658105+00:00'
last_modified: 2022-08-31 21:11:39.254317
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG22381
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG22381
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྤྱིར་བསྟན་གྱི་རྣམ་བཤད་ཐུབ་བསྟན་རིན་པོ་ཆེ་གསལ་བའི་སྒྲོན་མེ།
  author: སྒོ་མང་དཔོན་སློབ་སྐལ་བཟང་དངོས་གྲུབ།
statistics:
  ocr_word_mean_confidence_index: 0.6675780284056875
  ocr_word_median_confidence_index: 0.7300000190734863
quality: null
bases:
  I1KG22413:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22413
      total_pages: 70
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG22413.txt
    statistics:
      ocr_word_median_confidence_index: 0.7300000190734863
      ocr_word_mean_confidence_index: 0.6675780284056875
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
