id: IBBEEE677
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T23:25:37+00:00'
last_modified: '2022-06-08T13:20:00.507799+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG22381
  title: སྤྱིར་བསྟན་གྱི་རྣམ་བཤད་ཐུབ་བསྟན་རིན་པོ་ཆེ་གསལ་བའི་སྒྲོན་མེ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '2789':
      image_group_id: I1KG22413
      title: Volume 1 of spyir bstan gyi rnam bshad thub bstan rin po che gsal ba'i
        sgron me/
      total_pages: 70
      order: 1
      base_file: 2789.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
