id: P007026
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG22381
  title: སྤྱིར་བསྟན་གྱི་རྣམ་བཤད་ཐུབ་བསྟན་རིན་པོ་ཆེ་གསལ་བའི་སྒྲོན་མེ།
  author: ''
  volumes:
    e0c9cb91e7394381af8be35557ee6326:
      image_group_id: I1KG22413
      title: Volume 1 of spyir bstan gyi rnam bshad thub bstan rin po che gsal ba'i
        sgron me/
      volume_number: 1
      total_pages: 70
      base_file: v001.txt
