id: P007026
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG22381
  title: སྤྱིར་བསྟན་གྱི་རྣམ་བཤད་ཐུབ་བསྟན་རིན་པོ་ཆེ་གསལ་བའི་སྒྲོན་མེ།
  author: ''
  volumes:
    36b38c1dba404aa0b859f4c617f77e64:
      image_group_id: I1KG22413
      title: ''
      volume_number: 1
      total_pages: 70
ebook_metadata:
  title: སྤྱིར་བསྟན་གྱི་རྣམ་བཤད་ཐུབ་བསྟན་རིན་པོ་ཆེ་གསལ་བའི་སྒྲོན་མེ།
  author: ''
  sku: P007026
  cover: cover.jpg
  layers:
  - pagination
